- alias: 'Livingroom TV Set'
  description: 'Sets inputs and otputs for livingroom TV'
  trigger:
    - platform: state
      entity_id: input_select.livingroom_tv_source
  action:
    - service: script.turn_off
      entity_id: script.livingroom_tv_set

    - service: script.turn_on
      entity_id: script.livingroom_tv_set

- alias: 'Livingroom Harmony Hub Turn On TV'
  description: 'turns on TV when user clicks WatchTV'
  trigger:
    - platform: state
      entity_id: switch.harmony_hub_livingroom_watch_tv
      to: "on"
  action:
    service: media_player.turn_on
    entity_id: media_player.livingroom_tv