- alias: Hallway Bedroom Wall Light Set By Sun
  description: 'This automation will turn on wall lights in hallway when its sunset, and turn it off when its sunrise'
  trigger:
    - event: sunset
      offset: -00:59:00
      platform: sun
    - event: sunrise
      offset: +00:59:00
      platform: sun
  action:
    choose:
      - conditions: "{{ states.input_boolean.guest_mode.state == 'on' or (states.device_tracker.stefans_iphone.state == 'home' or states.device_tracker.stefans_iphone_cloud.state == 'home') and states.device_tracker.anjas_iphone.state == 'home' }}"
        sequence:
          service: >
            {% if trigger.event == 'sunset' %}
              light.turn_on
            {% elif trigger.event == 'sunrise' %}
                light.turn_off
            {% endif %}
          target:
            entity_id: light.hallway_bedroom_wall_light
  