- id: '1592937215382'
  alias: Bedroom Sensor Detected
  description: If its triggers between 23.00 - 08.00, it turns bed led strip on
  trigger:
  - entity_id: binary_sensor.motion_sensor_bedroom_left, binary_sensor.motion_sensor_bedroom_right
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '23:00:00'
    before: 08:00:00
    condition: time
  action:
  - data: {}
    entity_id: switch.bedroom_led_light_trafo
    service: switch.turn_on
- id: '1592938524703'
  alias: Bedroom Turn Off Bed Lights
  description: Turning bed ledstrip lights and trafo when no movement is detected
  trigger:
  - entity_id: binary_sensor.motion_sensor_bedroom_right,binary_sensor.motion_sensor_bedroom_left
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.bedroom_go_color_bed, light.bedroom_go_temp_bed
    service: light.turn_off
  - data: {}
    entity_id: switch.bedroom_led_light_trafo
    service: switch.turn_off
- id: '1593092839889'
  alias: Terace Turn On Wall Lights
  description: Turn on lights after sunset and offset
  trigger:
  - event: sunset
    offset: -00:59:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: switch.terace_wall_light
    service: switch.turn_on
- id: '1593093255568'
  alias: Terace Turn Off Wall Lights
  description: Turn off wall light on terace when is dawn
  trigger:
  - event: sunrise
    offset: -00:45:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: switch.terace_wall_light
    service: switch.turn_off
- id: '1593093721068'
  alias: Livingroom AboveTV Keep on
  description: Keeps trafo turned on whole time in order to see zigbee controller
    for abovetv ledstrip
  trigger:
  - entity_id: switch.living_room_above_tv_led
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: switch.living_room_above_tv_led
    service: switch.turn_on
- id: '1593629260708'
  alias: Rotary Button AboveTv
  description: ''
  trigger:
  - event_data:
      action: double_click
    event_type: esphome.above_tv_button
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: light.livingroom_go_temp_abovetv
    service: light.turn_off
  - data: {}
    entity_id: light.livingroom_go_color_abovetv
    service: light.turn_on
- id: '1593960834082'
  alias: Teraace heater set to off
  description: If someone turns on the hater, automaticallz turn off
  trigger:
  - entity_id: switch.terace_heater
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.terace_heater
    service: switch.turn_off
- id: '1595183286313'
  alias: Bedroom AC turn On Color LedWall
  description: ''
  trigger:
  - entity_id: light.bedroom_ac_ledstrip_wall
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      brightness: 254
      rgb_color:
      - 255
      - 0
      - 0
    entity_id: light.bedroom_go_color_wall
    service: light.turn_on
- id: '1595183556064'
  alias: Bedroom AC turn off Color LedWall
  description: ''
  trigger:
  - entity_id: light.bedroom_ac_ledstrip_wall, light.bedroom_go_color_wall
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.bedroom_go_color_wall
    service: light.turn_off
- id: '1604097341808'
  alias: Livinngroom belowtv switch always on
  description: ''
  trigger:
  - platform: state
    entity_id: switch.living_room_below_tv_led
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.living_room_below_tv_led
  mode: single
- id: '1604097639894'
  alias: Kitchen Working Desk Pre-Trafo Always On
  description: ''
  trigger:
  - platform: state
    entity_id: switch.kitchen_pre_trafo_working_desk_light
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.kitchen_pre_trafo_working_desk_light
  mode: single
- id: '1623164801824'
  alias: Plex light control
  description: ''
  use_blueprint:
    path: rhl2401/plex_light_dimmer.yaml
    input:
      topic: tautulli
      light: light.livingroom_wled_below_tv
- id: '1624958902748'
  alias: Turn Off All Lights VM
  description: When vacation mode is turned on, turn off all lights at 01:00 am
  trigger:
  - platform: time
    at: 01:00:00
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - service: script.turn_on
    target:
      entity_id: script.turn_off_all_lights_and_devices
  - service: persistent_notification.create
    data:
      message: 01:00 - All Lights turned off
      title: Automation kicks in
  mode: single
- id: '1632074139949'
  alias: Terace Button
  description: ''
  use_blueprint:
    path: Drafted/aqara-buttons-all-in-one-zigbee2mqtt.yaml
    input:
      action_sensor: sensor.terace_button
      single_action:
      - type: toggle
        device_id: 5e6ea5be8424961013949a7be4c98e3a
        entity_id: switch.terace_main_light
        domain: switch
      double_action:
      - type: toggle
        device_id: 26a1f21e11749e64a3e7b4d3039477f7
        entity_id: switch.terace_wall_light
        domain: switch
      hold_action:
      - service: cover.open_cover
        entity_id:
        - cover.ds_d
        - cover.ds_s
        - cover.ds_l
- id: '1638978737664'
  alias: Livingroom Cube
  description: Operations with aqara cube in livingroom
  use_blueprint:
    path: luckypoppy/z2m-xiaomi-cube-controller.yaml
    input:
      remote: sensor.livingroom_cube_action
      doubletap_face_0:
      - service: persistent_notification.create
        data:
          message: Double tap
          title: Double tap
          notification_id: Double tap
      flipped90_face_0:
      - service: script.turn_on
        target:
          entity_id: script.livingroom_romantic_scene
      flipped180_face_0:
      - service: persistent_notification.create
        data:
          message: FLip the cube 180
          title: FLip the cube 180
          notification_id: FLip the cube 180
      rotate_cw_face_0:
      - service: persistent_notification.create
        data:
          message: Roatate clockwise
          title: Roatate clockwise
          notification_id: Roatate clockwise
      rotate_ccw_face_0:
      - service: persistent_notification.create
        data:
          message: Roatate counter clockwise
          title: Roatate counter clockwise
          notification_id: Roatate counter clockwise
      slide_face_1:
      - service: persistent_notification.create
        data:
          message: Slide the cube with face 1 up
          title: Slide the cube with face 1 up
          notification_id: Slide the cube with face 1 up
      doubletap_face_1:
      - service: persistent_notification.create
        data:
          message: Double tap the cube with face 1 up
          title: Double tap the cube with face 1 up
          notification_id: Double tap the cube with face 1 up
      flipped90_face_1:
      - service: persistent_notification.create
        data:
          message: Flip the cube 90 degrees to face 1
          title: Flip the cube 90 degrees to face 1
          notification_id: Flip the cube 90 degrees to face 1
      flipped180_face_1:
      - service: persistent_notification.create
        data:
          message: Flip the cube 180 degrees to face 1
          title: Flip the cube 180 degrees to face 1
          notification_id: Flip the cube 180 degrees to face 1
      rotate_cw_face_1:
      - service: persistent_notification.create
        data:
          message: Rotate cube clockwise with face 1 up
          title: Rotate cube clockwise with face 1 up
          notification_id: Rotate cube clockwise with face 1 up
      rotate_ccw_face_1:
      - service: persistent_notification.create
        data:
          message: Rotate cube counter clockwise with face 1 up
          title: Rotate cube counter clockwise with face 1 up
          notification_id: Rotate cube counter clockwise with face 1 up
      slide_face_2:
      - service: persistent_notification.create
        data:
          message: Slide the cube with face 2 up
          title: Slide the cube with face 2 up
          notification_id: Slide the cube with face 2 up
      doubletap_face_2:
      - service: persistent_notification.create
        data:
          message: Double tap the cube with face 2 up
          title: Double tap the cube with face 2 up
          notification_id: Double tap the cube with face 2 up
      flipped90_face_2:
      - service: persistent_notification.create
        data:
          message: Flip the cube 90 degrees to face 2
          title: Flip the cube 90 degrees to face 2
          notification_id: Flip the cube 90 degrees to face 2
      flipped180_face_2:
      - service: persistent_notification.create
        data:
          message: Flip the cube 180 degrees to face 2
          title: Flip the cube 180 degrees to face 2
          notification_id: Flip the cube 180 degrees to face 2
      rotate_cw_face_2:
      - service: persistent_notification.create
        data:
          message: Rotate cube clockwise with face 2 up
          title: Rotate cube clockwise with face 2 up
          notification_id: Rotate cube clockwise with face 2 up
      rotate_ccw_face_2:
      - service: persistent_notification.create
        data:
          message: Rotate cube counter clockwise with face 2 up
          title: Rotate cube counter clockwise with face 2 up
          notification_id: Rotate cube counter clockwise with face 2 up
      slide_face_3:
      - service: persistent_notification.create
        data:
          message: Slide the cube with face 3 up
          title: Slide the cube with face 3 up
          notification_id: Slide the cube with face 3 up
      doubletap_face_3:
      - service: persistent_notification.create
        data:
          message: Double tap the cube with face 3 up
          title: Double tap the cube with face 3 up
          notification_id: Double tap the cube with face 3 up
      flipped90_face_3:
      - service: persistent_notification.create
        data:
          message: Flip the cube 90 degrees to face 3
          title: Flip the cube 90 degrees to face 3
          notification_id: Flip the cube 90 degrees to face 3
      flipped180_face_3:
      - service: persistent_notification.create
        data:
          message: Flip the cube 180 degrees to face 3
          title: Flip the cube 180 degrees to face 3
          notification_id: Flip the cube 180 degrees to face 3
      rotate_cw_face_3:
      - service: persistent_notification.create
        data:
          message: Rotate cube clockwise with face 3 up
          title: Rotate cube clockwise with face 3 up
          notification_id: Rotate cube clockwise with face 3 up
      rotate_ccw_face_3:
      - service: persistent_notification.create
        data:
          message: Rotate cube counter clockwise with face 3 up
          title: Rotate cube counter clockwise with face 3 up
          notification_id: Rotate cube counter clockwise with face 3 up
      slide_face_4:
      - service: persistent_notification.create
        data:
          message: Slide the cube with face 4 up
          title: Slide the cube with face 4 up
          notification_id: Slide the cube with face 4 up
      doubletap_face_4:
      - service: persistent_notification.create
        data:
          message: Double tap the cube with face 4 up
          title: Double tap the cube with face 4 up
          notification_id: Double tap the cube with face 4 up
      flipped90_face_4:
      - service: persistent_notification.create
        data:
          message: Flip the cube 90 degrees to face 4
          title: Flip the cube 90 degrees to face 4
          notification_id: Flip the cube 90 degrees to face 4
      flipped180_face_4:
      - service: persistent_notification.create
        data:
          message: Flip the cube 180 degrees to face 4
          title: Flip the cube 180 degrees to face 4
          notification_id: Flip the cube 180 degrees to face 4
      rotate_cw_face_4:
      - service: persistent_notification.create
        data:
          message: Rotate cube clockwise with face 4 up
          title: Rotate cube clockwise with face 4 up
          notification_id: Rotate cube clockwise with face 4 up
      rotate_ccw_face_4:
      - service: persistent_notification.create
        data:
          message: Rotate cube counter clockwise with face 4 up
          title: Rotate cube counter clockwise with face 4 up
          notification_id: Rotate cube counter clockwise with face 4 up
      slide_face_5:
      - service: persistent_notification.create
        data:
          message: Slide the cube with face 5 up
          title: Slide the cube with face 5 up
          notification_id: Slide the cube with face 5 up
      doubletap_face_5:
      - service: persistent_notification.create
        data:
          message: Double tap the cube with face 5 up
          title: Double tap the cube with face 5 up
          notification_id: Double tap the cube with face 5 up
      flipped90_face_5:
      - service: persistent_notification.create
        data:
          message: Flip the cube 90 degrees to face 5
          title: Flip the cube 90 degrees to face 5
          notification_id: Flip the cube 90 degrees to face 5
      flipped180_face_5:
      - service: persistent_notification.create
        data:
          message: Flip the cube 180 degrees to face 5
          title: Flip the cube 180 degrees to face 5
          notification_id: Flip the cube 180 degrees to face 5
      rotate_cw_face_5:
      - service: persistent_notification.create
        data:
          message: Rotate cube clockwise with face 5 up
          title: Rotate cube clockwise with face 5 up
          notification_id: Rotate cube clockwise with face 5 up
      rotate_ccw_face_5:
      - service: persistent_notification.create
        data:
          message: Rotate cube counter clockwise with face 5 up
          title: Rotate cube counter clockwise with face 5 up
          notification_id: Rotate cube counter clockwise with face 5 up
      shake:
      - service: braviatv_psk.bravia_command
        data:
          entity_id: media_player.livingroom_bravia
          command_id: ChannelUp
      fall:
      - service: persistent_notification.create
        data:
          message: Drop the cube
          title: Drop the cube
          notification_id: Drop the cube
- id: '1639521064597'
  alias: IKEA Symfonisk Black Hallway Controler
  description: Sets different lights, and double, tripple tap actions
  use_blueprint:
    path: EPMatt/ikea_e1744.yaml
    input:
      integration: Zigbee2MQTT
      helper_last_controller_event: input_text.ikea_symfonisk_blueprint_helper
      controller_entity: sensor.ikea_symfonisk_action
      action_rotate_left:
      - device_id: 45d0465cd0dc95de3e6d426130ae4104
        domain: light
        entity_id: light.livingroom_ceiling_led_1
        type: brightness_decrease
      - type: turn_off
        device_id: 45d0465cd0dc95de3e6d426130ae4104
        entity_id: light.terace_spot_1
        domain: light
      action_rotate_right:
      - device_id: 45d0465cd0dc95de3e6d426130ae4104
        domain: light
        entity_id: light.livingroom_ceiling_led_2
        type: brightness_increase
      - device_id: 45d0465cd0dc95de3e6d426130ae4104
        domain: light
        entity_id: light.livingroom_ceiling_led_1
        type: brightness_increase
      action_click_double:
      - service: icloud.play_sound
        data:
          account: stefan.cv5@gmail.com
          device_name: stefansiphone
      - service: icloud.play_sound
        data:
          account: permanentnosiva@icloud.com
          device_name: anjasiphone
