#start_time:
default_config:
my:
ios: !include ios_settings.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.9
    - 172.17.0.12
    - 172.17.0.11
    - 172.17.0.10
alert: !include_dir_named alerts/
alarm_control_panel:
  - platform: manual
    code: !secret alarm_code 
    arming_time: 5
    delay_time: 5
    trigger_time: 5
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  packages: !include_dir_named packages/
  media_dirs:
    local: /media

stream:
camera: !include_dir_merge_list cameras

proximity: !include_dir_named proximity

# influxdb:
#   host: !secret unraid_ip
#   port: !secret influxdb_port
#   username: !secret influxdb_username
#   password: !secret influxdb_token
#   database: !secret influxdb_database

notify: !include_dir_merge_list notify/
group: !include groups.yaml
scene: !include_dir_merge_list scenes 
  
binary_sensor: !include_dir_merge_list binary_sensors/
sensor: !include_dir_merge_list sensors/
input_boolean: !include_dir_named helpers/input_boolean/
input_number: !include_dir_named helpers/input_number/
input_select: !include_dir_named helpers/input_select/
input_text: !include_dir_named  helpers/input_text/
input_datetime: !include_dir_named input_datetime/
light: !include_dir_merge_list lights 

script: !include_dir_named 1scripts/
automation: !include automations.yaml
automation old: !include_dir_merge_list 1automations

#Google calendar
# google:
#   client_id: !secret google_calendar_client_id
#   client_secret: !secret google_calendar_client_secret
#   track_new_calendar: true

# alexa_media:
#   accounts:
#     email: !secret amazon_user
#     password: !secret amazon_password
#     url: "amazon.com"

alexa:
  smart_home:

# air_quality:
#   - platform: opensensemap
#     station_id: 5c424b321b7ca800199ad862
wake_on_lan:

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret base_local_ha_uri
    cache: true
#media devices
media_player: !include_dir_merge_list media_player/
# webostv:
#   host: !secret office_tv_ip
#   name: Office TV
#   turn_on_action:
#     service: wake_on_lan.send_magic_packet
#     data:
#       mac: !secret office_tv_mac_address
#       broadcast_address: !secret unraid_ip
#   customize:
#     sources:
#       - youtube
#       - netflix
#       - eon
#       # - Spotify
#       - plex
#       # - Chromecast
spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret_id


#devices
aquaariston: !include aquaariston.yaml


