start_time:
default_config:
my:
ios: !include ios_settings.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.9
    - 172.17.0.12
    - 172.17.0.11
    - 172.17.0.10
alert: !include_dir_named alerts/
alarm_control_panel:
  - platform: manual
    code: !secret alarm_code 
    arming_time: 5
    delay_time: 5
    trigger_time: 5
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  packages: !include_dir_named packages/
  media_dirs:
    local: /media

stream:
camera: !include_dir_merge_list cameras

proximity: !include_dir_named proximity

influxdb:
  host: !secret unraid_ip
  port: !secret influxdb_port
  username: !secret influxdb_username
  password: !secret influxdb_token
  database: !secret influxdb_database

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret base_local_ha_uri
    cache: true

notify: !include_dir_merge_list notify/
group: !include groups.yaml
scene: !include_dir_merge_list scenes 

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret_id
  
binary_sensor: !include_dir_merge_list binary_sensors/
sensor: !include_dir_merge_list sensors/
input_boolean: !include_dir_named helpers/input_boolean/
input_number: !include_dir_named helpers/input_number/
input_select: !include_dir_named helpers/input_select/
input_text: !include_dir_named  helpers/input_text/
input_datetime: !include_dir_named input_datetime/
light: !include_dir_merge_list lights 

script: !include_dir_named 1scripts/
automation: !include automations.yaml
automation old: !include_dir_merge_list 1automations

#Google calendar
# google:
#   client_id: !secret google_calendar_client_id
#   client_secret: !secret google_calendar_client_secret
#   track_new_calendar: true

# alexa_media:
#   accounts:
#     email: !secret amazon_user
#     password: !secret amazon_password
#     url: "amazon.com"

alexa:
  smart_home:

air_quality:
  - platform: opensensemap
    station_id: 5c424b321b7ca800199ad862
wake_on_lan:
webostv:
  host: !secret office_tv_ip
  name: Office TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret office_tv_mac_address
      broadcast_address: !secret unraid_ip
  customize:
    sources:
      - youtube
      - netflix
      - eon
      # - Spotify
      - plex
      # - Chromecast

media_player: !include_dir_merge_list media_player/

aquaariston:
  username: !secret ariston_username
  password: !secret ariston_password
  type: "velis"
  logging: "WARNING"                  # indicates logging level ("CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG", "NOTSET"). Default is "DEBUG"
  #path: "/home/homeassistant/.homeassistant/aqua_http_data" # Forces new path for storing files. SET NEW VALUES IF "/config" IS NOT CORRECT
  polling: 1.2                        # indicates relative time for requests waiting. Increase in case of timeouts. Default is 1.0
  store_config_files: true            # indicates if to store API data in a folder
  switches:
    - eco                             # switches ECO mode
    - power                           # switches power
  binary_sensors:
    - antilegionella                  # indicates antilegionella status
    - changing_data                   # indicates ongoing configuration on server by the API
    - eco                             # indicates ECO mode status
    - heating                         # indicates ongoing heating
    - online                          # indicates API online status
    - power                           # indicates power status
    - update                          # indicates API update
  sensors:
    - antilegionella_set_temperature  # antilegionella temperature
    - current_temperature             # current temperature
    - energy_use_in_day               # energy use in last day
    - energy_use_in_month             # energy use in last week
    - energy_use_in_week              # energy use in last month
    - energy_use_in_year              # energy use in last year
    - errors                          # errors
    - mode                            # manual or time program mode
    - remaining_time                  # remaining time for heating
    - required_showers                # required amount of showers (might not work on all models)
    - required_temperature            # required temperature (simulated by API itself for some models)
    - showers                         # estimated amount of average showers
    - temperature_mode                # indicates if required temeparture is based on required temperature or required showers
    - time_program                    # time program schedule
  selector:
    - mode                            # boiler mode selector