default_config:
my:
ios: !include ios_settings.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.9
    - 172.17.0.12
    - 172.17.0.11
    - 172.17.0.10
alert: !include_dir_named alerts/
frontend:
  themes: !include_dir_merge_named themes
switch: !include switches.yaml
homeassistant:
  packages: !include_dir_named packages/
  media_dirs:
    local: /media


influxdb:
  host: !secret unraid_ip
  port: 8088
  username: homeassistant
  password: !secret influxdb_token
  database: homeassistant

# Text to speech
tts:
  - platform: google_translate
    base_url: http://192.168.1.79:8123
    cache: true

group: !include groups.yaml
scene: !include_dir_merge_list scenes 

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key
  accounts:
    livingroom:
      sp_dc: !secret spotcast_livingroom_sp_dc
      sp_key: !secret spotcast_livingroom_sp_key
    bedroom:
      sp_dc: !secret spotcast_bedroom_sp_dc
      sp_key: !secret spotcast_bedroom_sp_key
    office:
      sp_dc: !secret spotcast_office_sp_dc
      sp_key: !secret spotcast_office_sp_key

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret_id
  
binary_sensor: !include_dir_merge_list binary_sensors/
sensor: !include_dir_merge_list sensors/
input_boolean: !include_dir_named input_boolean/
input_number: !include_dir_named input_number/
input_select: !include_dir_named input_select/
input_text: !include_dir_named  input_text/
input_datetime: !include_dir_named input_datetime/
light: !include_dir_merge_list lights 
timer: !include_dir_named timers/
script: !include_dir_named scripts/
automation: !include automations.yaml
automation old: !include_dir_merge_list automations

#Google calendar
# google:
#   client_id: !secret google_calendar_client_id
#   client_secret: !secret google_calendar_client_secret
#   track_new_calendar: true

wake_on_lan:
webostv:
  host: !secret office_tv_ip
  name: Office TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret office_tv_mac_address
  customize:
    sources:
      - youtube
      - netflix
      - eon
      # - Spotify
      - plex
      # - Chromecast

media_player: !include_dir_merge_list media_player/