- alias: Reload covers when unavailable
  description: 'If covers goes to unavailable state try to reload cloud api somfy integration'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: cover.rs_l
      for: 00:00:10
      to: unavailable
  action:
    - delay: 00:00:04
    - service: homeassistant.reload_config_entry
      entity_id: cover.rs_l
    # - service: persistent_notification.create
    #   data:
    #     title: 'Covers recovered!'
    #     message: 'Covers indeed.'