- alias: "Bedroom Baby Action Button"
  description: "When its clicked sets lights to on and prepare evrything for baby"
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_bed_right_rotary_button
  action:
   service: input_boolean.toggle
   target:
    entity_id: input_boolean.baby_mode_button