- alias: "Bedroom Bed Led Strip Movement On"
  description: "Turns on when detected movement around bed"
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_bed_motion_sensors
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_bed_motion_sensors
      to: 'off'
      for: '00:00:40'
  condition:
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.bedroom_illuminance_lux
          below: 10
        - condition: time
          after: input_datetime.time_when_bed_motion_sensors_starts_to_trigger_light
          before: input_datetime.time_when_bed_motion_sensors_ends_to_trigger_light
  action:
    service: >
       switch.turn_{{trigger.to_state.state}}
    entity_id: switch.bedroom_led_light_trafo