- alias: 'Bedroom toggle lights by left lamp light'
  trigger:
    - platform: state
      entity_id: light.bedroom_left_lamp
      to: 'off'
  action:
    - choose:
      - conditions:
          - condition: template
            value_template: "{{is_state('light.bedroom_main_light', 'on')}}"
        sequence:
          - service: light.turn_off
            entity_id: light.bedroom_main_light
    - choose:
      - conditions:
          - condition: template
            value_template: "{{is_state('light.bedroom_left_lamp', 'on') and is_state('light.bedroom_right_lamp', 'on')}}"
        sequence:
          - service: light.turn_off
            entity_id: light.bedroom_right_lamp
 
- alias: 'Bedroom toggle lights by right lamp light'
  trigger:
    - platform: state
      entity_id: light.bedroom_right_lamp
      to: 'off'
  action:
    - choose:
      - conditions:
          - condition: template
            value_template: "{{is_state('light.bedroom_main_light', 'on')}}"
        sequence:
          - service: light.turn_off
            entity_id: light.bedroom_main_light
    - choose:
      - conditions:
          - condition: template
            value_template: "{{is_state('light.bedroom_left_lamp', 'on') and is_state('light.bedroom_right_lamp', 'on')}}"
        sequence:
          - service: light.turn_off
            entity_id: light.bedroom_right_lamp,light.bedroom_left_lamp
 