- alias: 'Toggle the main light based on door sensor'
  trigger:
    - platform: state
      entity_id: binary_sensor.rack_door
  action:
    - service_template: >
        {% if states('binary_sensor.rack_door') == "on" %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.rack_light