#SINGLE SHORT CLICK

- alias: Bedroom Entrance Wall Ledstrip toggle via encoder
  id: bedroom_entrance_wall_short_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: single_short_click_1
  condition: "{{as_timestamp(now()) - as_timestamp(states.light.bedroom_main_light.last_changed) > 1}}"
  action:
    - service: light.toggle
      entity_id: light.bedroom_wall_wled

- alias: Bedroom Entrance Ceiling Ledstrip toggle via encoder
  id: bedroom_entrance_ceiling_short_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: single_short_click_2
  action:
    - service: light.toggle
      target:
        entity_id: light.bedroom_ceiling_wled

- alias: Bedroom Entrance TV toggle via encoder
  id: bedroom_entrance_tv_short_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: single_short_click_3
  action:
    - service: braviatv_psk.bravia_open_app
      data:
        entity_id: media_player.bedroom_tv
        uri: >-
          com.sony.dtv.com.ug.eon.android.tv.com.ug.eon.android.tv.TvActivity

#SINGLE LONG CLICK

- alias: Bedroom Entrance Wall Ledstrip Single Long Click
  id: bedroom_entrance_wall_single_long_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: single_long_click_1
  action:
    - service: light.turn_off
      target:
        entity_id: light.bedroom_wall_wled

- alias: Bedroom Entrance Ceiling Ledstrip Single Long Click
  id: bedroom_entrance_ceiling_single_long_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: single_long_click_2
  action:
    - service: light.turn_off
      target:
        entity_id: light.bedroom_ceiling_wled

- alias: Bedroom Entrance TV Single Long Click
  id: bedroom_entrance_tv_single_long_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: single_long_click_3
  action:
    - service: media_player.turn_off
      entity_id: media_player.bedroom_tv

#DOUBLE CLICK

- alias: Bedroom Entrance Wall Double Click
  id: bedroom_entrance_wall_double_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: double_click_1
  action:
    - choose:
      - conditions: "{{is_state ('light.bedroom_ceiling_wled','on')}}"
        sequence:
          service: light.turn_on
          target:
            entity_id: light.bedroom_wall_wled
          data:
            brightness: "{{ state_attr('light.bedroom_ceiling_wled', 'brightness')}}"
            effect: "{{ state_attr('light.bedroom_ceiling_wled', 'effect')}}"
            rgb_color: "{{state_attr('light.bedroom_ceiling_wled', 'rgb_color')}}"
      - conditions: "{{is_state ('light.bedroom_ceiling_wled','off')}}"
        sequence:
          service: script.turn_on
          target:
            entity_id: script.light_wled_on
          data:
            variables:
              brightness: '100'
              intensity: '100'
              speed: '100'
              palette: Default
              wled_light_entity: light.bedroom_wall_wled
              wled_color_palette_entity: select.bedroom_wall_wled_color_palette
              wled_intensity_entity: number.bedroom_ceiling_wled_intensity
              wled_speed_entity: number.bedroom_ceiling_wled_speed
              rgb_random: 'True'
              effect_random: 'True'

- alias: Bedroom Entrance Ceiling Double Click
  id: bedroom_entrance_ceiling_double_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: double_click_2
  action:
    service: script.turn_on
    target:
      entity_id: script.light_wled_on
    data:
      variables:
        brightness: 255
        intensity: 255
        speed: 255
        palette: Default
        wled_light_entity: light.bedroom_ceiling_wled
        wled_color_palette_entity: select.bedroom_wall_wled_color_palette
        wled_intensity_entity: number.bedroom_ceiling_wled_intensity
        wled_speed_entity: number.bedroom_ceiling_wled_speed
        rgb_random: 'True'
        effect_random: 'True'

- alias: Bedroom Entrance TV Double Click
  id: bedroom_entrance_tv_double_click
  trigger:
    platform: event
    event_type: esphome.bedroom_entrance
    event_data:
      type: double_click_3
  action:
    service: script.turn_on
    target:
      entity_id: script.bedroom_tv_audio_in_bathroom

#ROTARY ENCODER

- alias: 'Bedroom Entrance Ceiling Dimming via encoder'
  id: bedroom_entrance_ceiling_dimming_encoder
  trigger:
    - platform: state
      entity_id: sensor.bedroom_entrance_led_ceiling_dimmer
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state not in ['unavailable','unknown'] }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.bedroom_ceiling_wled
              data:
                brightness: >
                  {{states('sensor.bedroom_entrance_led_ceiling_dimmer') | int * 2.55 | round(0) }}

- alias: 'Bedroom Entrance Bedroom Wall Dimming via encoder' 
  id: bedroom_entrance_wall_dimming_encoder 
  trigger:
    - platform: state
      entity_id: sensor.bedroom_entrance_led_wall_dimmer
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state not in ['unavailable','unknown'] }}"
          sequence:
            - service: light.turn_on
              entity_id: light.bedroom_wall_wled
              data:
                brightness: >
                  {{states('sensor.bedroom_entrance_led_wall_dimmer') | int }}

- alias: 'Bedroom Entrance TV Volume via encoder'
  id: bedroom_entrance_tv_volume_encoder 
  trigger:
    - platform: state
      entity_id: sensor.bedroom_entrance_actuator_1
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state not in ['unavailable','unknown'] }}"
          sequence:
            - service: media_player.volume_set
              entity_id: media_player.bedroom_ceiling_speaker
              data:
                volume_level: >
                  {{ states('sensor.bedroom_entrance_actuator_1')|float/100 }}