#SINGLE SHORT CLICK

- alias: Hallway Wardrobe Ledstrip Short Button
  id: hallway_wardrobe_ledstrip_short_button
  trigger:
    platform: event
    event_type: esphome.hallway
    event_data:
      type: single_short_click_2
  action:
    choose:
      - conditions: "{{ is_state('light.hallway_wled_segment_1', 'off') and is_state('light.hallway_wled_segment_2', 'off') and is_state('light.hallway_wled_segment_3', 'off')}}"
        sequence:
          service: light.turn_on
          entity_id: light.hallway_wled_segment_1
          data:
              effect: "Solid"
              rgb_color: [255,212,138]
              brightness: 255
      - conditions:  "{{ is_state('light.hallway_wled_segment_1', 'on') and is_state('light.hallway_wled_segment_2', 'off') and is_state('light.hallway_wled_segment_3', 'off')}}"
        sequence:
          service: light.turn_on
          entity_id: light.hallway_wled_segment_2
          data:
              effect: "Solid"
              rgb_color: [255,212,138]
              brightness: 255
      - conditions:  "{{ is_state('light.hallway_wled_segment_1', 'on') and is_state('light.hallway_wled_segment_2', 'on') and is_state('light.hallway_wled_segment_3', 'off')}}"
        sequence:
          service: light.turn_on
          entity_id: light.hallway_wled_segment_3
          data:
              effect: "Solid"
              rgb_color: [255,212,138]
              brightness: 255
      - conditions:  "{{ is_state('light.hallway_wled_segment_1', 'on') and is_state('light.hallway_wled_segment_2', 'on') and is_state('light.hallway_wled_segment_3', 'on')}}"
        sequence:
          service: light.turn_off
          entity_id: light.hallway_wled

#SINGLE LONG CLICK

- alias: Hallway Wardrobe_Ledstrip Long Click
  id: hallway_wardrobe_ledstrip_single_long_click
  trigger:
    platform: event
    event_type: esphome.hallway
    event_data:
      type: single_long_click_2
  action:
    - service: light.turn_on
      entity_id: light.hallway_wled
      data:
        effect: 'solid'

#DOUBLE CLICK

- alias: Hallway Actuator Double Click
  id:  hallway_actuator_double_click
  trigger:
    platform: event
    event_type: esphome.hallway
    event_data:
      type: double_click_2
  action:
    service: script.turn_on
    target:
      entity_id: script.light_wled_on
    data:
      variables:
        brightness: 255
        intensity: 255
        speed: 255
        palette: Default
        wled_light_entity: light.hallway_wled
        
        wled_intensity_entity: number.hallway_wled_intensity
        wled_speed_entity: number.hallway_wled_speed
        rgb_random: 'True'
        effect_random: 'True'

#ROTARY ENCODER

- alias: 'Hallway Wardrobe Ledstrip Dimmer'
  id: hallway_wardrobe_ledstrip_dimmer
  trigger:
    - platform: state
      entity_id: sensor.hallway_ledstrip_encoder
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state not in ['unavailable','unknown'] }}"
          sequence:
            - service: light.turn_on
              entity_id: light.hallway_wled
              data:
                brightness: >
                  {{states('sensor.hallway_ledstrip_encoder') | int * 2.55 | round(0) }}