- alias: Residents Away From Home
  trigger:
    - platform: state
      entity_id: 
        - device_tracker.stefans_iphone
        - device_tracker.anjas_iphone
      from: 'home'
      to: 'not_home'
  condition:
    - condition: template
      value_template: > 
        {{  states.input_boolean.guest_mode.state == 'off' and (states.device_tracker.stefans_iphone.state == 'not_home' or states.device_tracker.stefans_iphone_2.state == 'not_home') and states.device_tracker.anjas_iphone.state == 'not_home' }}
    - condition: state
      entity_id: input_boolean.guest_mode
      state:  'off'
  action:
    - service: persistent_notification.create
      data:
        title: 'Residents are not at home'
        message: "Turning all the lights and media."
    - service: script.turn_on
      entity_id: script.turn_off_all_lights_and_devices
    - service: alert.turn_off
      entity_id: alert.pick_up_laundry
    
