- alias: "Office Closet Lights Toggle By Door"
  description: "Turns on or off when doors open or close"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_closet
  action:
    - service: >
        {% if states('binary_sensor.office_closet') == "on" %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}     
      entity_id: light.office_closet_lights