- platform: group
  name: Bedroom Wled
  entities:
    - light.bedroom_wall_wled
    - light.bedroom_ceiling_wled

- platform: group
  name: Bedroom Below Bed
  entities:
    - light.bedroom_below_bed_cct
    - light.bedroom_below_bed_rgb

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_main_light
    - light.bedroom_left_lamp
    - light.bedroom_right_lamp
    

- platform: group
  name: Bedroom All Lights
  entities:
    - light.bedroom_bad_light_pre_trafo
    - light.bedroom_lights
    - light.bedroom_wardrobe_lights
    - light.bedroom_ceiling_wled
    - light.bedroom_wall_wled
    - light.bedroom_below_bed