- platform: group
  name:  Hallway Bedroom All Lights
  entities:
    - light.hallway_bedroom_main_light
    - light.hallway_bedroom_wall_light
    - light.toilet_light

- platform: group
  name:  Hallway Livingroom All Lights
  entities:
    - light.hallway_livingroom_main_light
    - light.hallway_wled
    - light.rack

- platform: group
  name: Both Hallways All lights
  entities:
    - light.hallway_bedroom_all_lights
    - light.hallway_livingroom_all_lights