- platform: group
  name: Kitchen all lights
  entities:
    - light.kitchen_gun
    - light.kitchen_desk

- platform: group
  name: Kitchen Desk
  entities:
    - light.wled_kitchen_segment_1
    - light.wled_kitchen_segment_2
    - light.wled_kitchen_segment_3