- platform: switch
  name:  Office Main Light
  entity_id:
    - switch.office_main_light

- platform: group
  name:  Office All Lights
  entities:
    - light.office_main_light
    - light.office_desk_lamp
    
