- alias: "Bedroom Audio TV Toggle"
  description: "When Bedroom TV is turned on, turn on audio ceilings in bedroom and set correct source"
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.bedroom_tv
      to:
        - "on"
        - "off"  
  action:
    - choose:
      - conditions:
          - condition: template
            value_template: "{{trigger.to_state.state == 'on'}}"
        sequence:
          - service: script.turn_on
            entity_id: script.set_speaker
            data:
              variables:
                speaker: "media_player.bedroom_ceiling_speaker"
                volume: "0.2"
                source: "Bedroom TV"
          - service: braviatv_psk.bravia_open_app
            data:
              entity_id: media_player.bedroom_tv
              uri: >-
                com.sony.dtv.com.ug.eon.android.tv.com.ug.eon.android.tv.TvActivity
          - delay: 00:00:05
          - service: braviatv_psk.bravia_command
            data:
              entity_id: media_player.bedroom_tv
              command_id: Confirm
      - conditions:
          - condition: template
            value_template: "{{trigger.to_state.state == 'off'}}"
        sequence:
          - service: media_player.turn_off
            entity_id: media_player.bedroom_ceiling_speaker


            

- alias: 'Sync bedroom speakers ceiling to tv volume'
  mode: single
  trigger:
  - platform: state
    entity_id: media_player.bedroom_tv
    attribute: volume_level
  - platform: state
    entity_id: media_player.bedroom_tv
    to: 'on'
  action:
    service: media_player.volume_set
    data:
      entity_id: media_player.bedroom_ceiling_speaker
      volume_level: "{{ state_attr(trigger.to_state.entity_id, 'volume_level') }}"