- alias: "Officeroom toggle by tv "
  description: "When Office TV is turned on, turn on zone 4 in office room and power off if tv is off"
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.office_tv
  action:
      - choose:
        - conditions:
            - condition: template
              value_template: "{{trigger.to_state.state == 'on'}}"
          sequence:
            - service: script.turn_on
              entity_id: script.set_speaker
              data:
                variables:
                  speaker: "media_player.office_shelf_speakers"
                  volume: "0.3"
                  source: "Office TV"
        - conditions:
            - condition: template
              value_template: "{{trigger.to_state.state == 'off'}}"
          sequence:
            - service: media_player.turn_off
              data:
                entity_id: media_player.office_shelf_speakers