- platform: template
  sensors:
    bedroom_bed_motion_right_on_last_changed:
      value_template: >
        {% if is_state('binary_sensor.bedroom_bed_left_motion', 'on') %}
          {{ as_timestamp(now()) - as_timestamp(states.binary_sensor.bedroom_bed_left_motion.last_changed) }}
        {% else %}
          {{ states('sensor.bedroom_bed_left_motion_last_occured') }}
        {% endif %}