- platform: template
  sensors:
    frontdoor_last_movement_time:
      value_template: "{{as_timestamp(states.binary_sensor.frontdoor_motion.last_changed) | timestamp_custom('%A %d-%b-%y, %H:%M:%S')}}"