- alias: Bathroom toggle based on thermostat
  trigger:
    # - platform: time
    #   at: input_datetime.time_when_boiler_goes_to_on
    - platform: state
      entity_id: sensor.aqua_ariston_current_temperature
  action:
      - choose:
        - conditions: "{{ states('sensor.aqua_ariston_current_temperature') | int < 50}}"
          sequence:
            service: switch.turn_on
            entity_id: switch.aqua_ariston_power
        - conditions: "{{ states('sensor.aqua_ariston_current_temperature') | int > 65}}"
          sequence:
            service: switch.turn_off
            entity_id: switch.aqua_ariston_power


# - alias: Bathroom turn off boiler at non_cheapest tarif
#   trigger:
#     - platform: time
#       at: input_datetime.time_when_boiler_goes_to_off
#   action:
#       service: switch.turn_off
#       entity_id: switch.aqua_ariston_power