- alias: Bathroom wled by washing machine
  description: 'Sets wled light above washing machine when starts to wash landry'
  trigger:
    - platform: state
      entity_id: sensor.washer
      to: 'on'
  condition:
    - condition: time
      after: "07:00:00"
      before: "00:00:00"
  action:
    - delay: 00:00:05
    - service: script.turn_on
      entity_id: script.play_notification
      data:
        variables:
          speaker: "media_player.bathroom_ceiling_speaker"
          source: "Primary Chromecast"
          volume: "0.4"
          custom_message: "Attention! Washing machine started. Remaining time is {{ states.sensor.washer.attributes.remain_time }} and program temperature is set to {{ states.sensor.washer.attributes.water_temp }}"
          platform: "tts.google_translate_say"
          delay: "00:00:03"
          chromecast_device: "media_player.system_chromecast"
    - service: light.turn_on
      entity_id: light.bathroom_wled
      data:
        effect: 'Washing Machine'

- alias: Bathroom washing machine completed
  description: 'Notify when washing laundry is finished'
  trigger:
    - platform: state
      entity_id: sensor.washer
      to: 'off'
  action:
    - choose:
      - conditions:
          - condition: time
            after: "07:00:00"
            before: "00:00:00"
        sequence:
          - service: script.turn_on
            entity_id: script.play_notification_everywhere
            data:
              variables:
                speaker: "media_player.bathroom_ceiling_speaker"
                source: "Primary Chromecast"
                volume: "0.3"
                custom_message: "Attention! Washing machine has finished washing the laundry."
                platform: "tts.google_translate_say"
                delay: "00:00:03"
                chromecast_device: "media_player.system_chromecast"
          - service: light.turn_off
            entity_id: light.bathroom_wled

    - service: input_boolean.turn_on
      entity_id: input_boolean.pickup_laundry
    - service: light.turn_off
      entity_id: light.bathroom_wled

- alias: Bathroom washing machine door closed
  description: 'sets input_boolean.pickup_laundry to off'
  trigger:
    - platform: state
      entity_id: binary_sensor.washer_door
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.pickup_laundry
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.pickup_laundry

- alias: Bathroom washing machine door sensor
  description: 'stops automation and sends an alert'
  trigger:
    - platform: state
      entity_id: binary_sensor.washer_door
      to: 'unavailable'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.pickup_laundry