- alias: 'Office Wardrobe Lights By Door sensors'
  description: 'toggle office wardrobe and closet lights by wardrobe and closet door sensor'
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.office_wardrobe_left_door
        - binary_sensor.office_wardrobe_right_door
  action:
    - service_template: >
        {% if states('binary_sensor.office_wardrobe_left_door') == "on" or states('binary_sensor.office_wardrobe_right_door') == "on" %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}  
      data_template:
        entity_id: >
          {% if trigger.to_state.entity_id == 'binary_sensor.office_wardrobe_left_door' %}
            light.office_wardrobe_left_left, light.office_wardrobe_left_right
          {% elif trigger.to_state.entity_id == 'binary_sensor.office_wardrobe_right_door' %}
            light.office_wardrobe_right_right, light.office_wardrobe_right_left
          {% else %}
            #DoNothing
          {% endif %}