- alias: 'Welcome lights on entrance'
  description: 'When nobody is in the home and when is dark, turn on a few lights'
  trigger:
    - platform: state
      entity_id: binary_sensor.nuki_door_state
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: template
          value_template: "{{ as_timestamp(now()) -  as_timestamp(states.binary_sensor.frontdoor_motion.last_changed) <= 40}}"
  action:
    - service: scene.turn_on
      entity_id: scene.welcome_home