#SINGLE SHORT CLICK

- alias: Livingroom Spotlights 2 via encoder
  id: livingroom_entrance_spotlights_2_short_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_short_click_1
  action:
    - service: light.toggle
      entity_id: light.livingroom_spotlights_2

- alias: Livingroom Ceiling LED 2 ESP
  id: kitchen_livingroom_ceiling_led_short_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_short_click_2
  action:
    - service: light.toggle
      entity_id: light.livingroom_ceiling_led_2

- alias: Kitchen Workingdesk Light via encoder
  id: kitchen_workingdesk_light_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_short_click_3
  action:
    - service: wled.effect
      data:
        entity_id: light.kitchen_wled
        palette: "Default"
        effect: "Solid"
    - service: light.toggle
      entity_id: light.kitchen_wled

- alias: Kitchen Actuator via encoder
  id: kitchen_actuator_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_short_click_4
  action:
    - service: script.turn_on
      entity_id: script.watch_tv_livingroom
      data:
        variables:
          tvsource: "SBB"

#SINGLE LONG CLICK

- alias: Kitchen Terace Spots Long Click
  id: kitchen_terace_spots_single_long_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_long_click_1
  action:
    - service: script.turn_off
      entity_id: script.spotlights_walking_effect
    - delay: 00:00:01
    - service: script.turn_on
      entity_id: script.spotlights_walking_effect
    # - service: light.turn_off
    #   entity_id: 
    #     - light.bedroom_go_temperature_wall
    #     - light.bedroom_go_color_wall

- alias: Kitchen Terace Ledstrip Long Click
  id: kitchen_terace_ledstrip_long_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_long_click_2
  action:
    - service: light.turn_off
      entity_id: 
        - light.livingroom_go_temp_teracewall
        - light.livingroom_go_color_teracewall

- alias: Kitchen Workdesk Long Click
  id: kitchen_workdesk_long_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_long_click_3
  action:
    - service: light.turn_off
      entity_id: light.kitchen_wled

- alias: Kitchen Actuator Long Click
  id: kitchen_actuator_long_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: single_long_click_4
  action:
    - service: media_player.turn_off
      entity_id: media_player.livingroom_tv

#DOUBLE CLICK

- alias: Kitchen Terace Spots Double Click
  id: kitchen_terace_spots_double_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: double_click_1
  variables:
    lights:
      - light.livingroom_spotlight_2_1
      - light.livingroom_spotlight_2_2
      - light.livingroom_spotlight_2_3
      - light.livingroom_spotlight_2_4
      - light.livingroom_spotlight_2_5
      - light.livingroom_spotlight_2_6
    on_lights: >
      {{ expand(lights) | selectattr('state','eq','on') | map(attribute='entity_id') | list }}
    off_lights: >
      {{ expand(lights) | selectattr('state','eq','off') | map(attribute='entity_id') | list }}
    on_count: >
      {{ on_lights | length }}
    next_light: >
      {%- if lights == off_lights %}
        {{ lights[0] }}
      {%- elif lights[:on_count] == on_lights and on_lights != lights %}
        {{ lights[on_count] }}
      {%- else %}
        off
      {%- endif %}
  action:
    - choose:
      - conditions:
        - condition: template
          value_template: "{{ next_light != 'off' }}"
        sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ next_light }}"
      default:
      - service: light.turn_off
        target:
          entity_id: "{{ on_lights }}"
      - service: light.turn_on
        target:
          entity_id: "{{ lights[0] }}"   

- alias: Kitchen Terace Ledstrip Double Click
  id: kitchen_terace_ledstrip_double_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: double_click_2
  action:
    - service: light.turn_off
      entity_id: light.livingroom_go_temp_teracewall       
    - service: light.turn_on
      entity_id: light.livingroom_go_color_teracewall
      data:
        rgb_color: ["{{range(256)|random}}","{{range(256)|random}}","{{range(256)|random}}"]

- alias: Kitchen Workdesk Ledstrip Double Click
  id: kitchen_workdesk_ledstrip_double_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: double_click_3
  action:
    - service: light.turn_on
      entity_id: light.kitchen_wled
      data:
        rgb_color: ["{{range(256)|random}}","{{range(256)|random}}","{{range(256)|random}}"]

- alias: Kitchen Actuator Double Click
  id: kitchen_actuator_double_click
  trigger:
    platform: event
    event_type: esphome.kitchen
    event_data:
      type: double_click_4
  action:
    # - service: persistent_notification.create
    #   data:
    #     title: 'This is a Kitchen short click 1 test'
    #     message: "Test indeed."
    # - service: switch.turn_on
    #   entity_id: switch.bedroom_led_light_trafo

    # - service: light.turn_off
    #   entity_id: light.bedroom_go_temp_bed       

    # - service: light.turn_on
    #   entity_id: light.bedroom_go_color_bed
    #   data:
    #     rgb_color: ["{{range(256)|random}}","{{range(256)|random}}","{{range(256)|random}}"]
