- platform: braviatv_psk
  name: bedroom_tv
  host: !secret bedroom_tv_ip
  psk: !secret psk_bedroom_tv
  mac: !secret bedroom_tv_mac
  amp: True
  android: True
  time_format: 24H
  user_labels: True

  