- platform: braviatv_psk
  host: !secret livingroom_tv_ip
  psk: !secret psk_livingroom_tv
  mac: !secret livingroom_tv_mac
  amp: True
  android: True
  time_format: 24H
  user_labels: True
  name: livingroom_bravia