- alias: Livingroom HarmonyHub State Change
  description: 'Livingroom HarmonyHub State Change from WatchTV to Off, make sure that tv SONY bravia IS TURNED OFF'
  trigger:
  - platform: state
    entity_id: select.harmony_hub_livingroom_activities
    from: 'Watch TV'
    to: 'PowerOff'
  action:
    if: "{{ is_state('media_player.livingroom_tv', 'playing') }}"
    then:
       - alias: "Set volume to 0 on tv"
         service: media_player.volume_set
         entity_id: media_player.livingroom_bravia
         data:
           volume_level: 0

- alias: Livingroom HarmonyHub Mute LivingroomTV
  description: 'Livingroom HarmonyHub State Change from WatchTV to Off, make sure that tv SONY bravia IS TURNED OFF'
  trigger:
  - platform: state
    entity_id: select.harmony_hub_livingroom_activities
    to: 'Watch TV'
  action:
    - delay: 00:00:05
    - if: "{{ is_state('media_player.livingroom_bravia', 'playing') }}"
      then:
       - alias: "Set volume to 0 on tv"
         service: media_player.volume_set
         entity_id: media_player.livingroom_bravia
         data:
           volume_level: 0