esphome:
  name: dimmerswitch_kitchen_zone1
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "ThePingInTheNorth"
  password: "lanister"
  ap:
    ssid: "PanicVIFI"
    password: "dubai.2020"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "lanister"
ota:
  password: "lanister"


sensor:
#KITCHEN WORKDESK CONTROL
  - platform: rotary_encoder
    name: "Kitchen workdesk ledstrip dimmer"
    id: kitchen_workdesk_ledstrip__dimmer
    pin_a: GPIO2
    pin_b: GPIO14
    min_value: 0
    max_value: 100
    resolution: 2
    filters:
      - delta: 4.0

#KITCHEN AMBIENT LEDSTRIP CONTROL
  - platform: rotary_encoder
    name: "Kitchen ambient ledstrip dimmer"
    id: kitchen_ambient_ledstrip_dimmer
    pin_a: GPIO12
    pin_b: GPIO13
    min_value: 0
    max_value: 100
    resolution: 2
    filters:
      - delta: 4.0
binary_sensor:
#KITCHEN WORKDESK CONTROL
  - platform: gpio
    id: kitchen_workdesk_ledstrip_switcher
    name: "Kitchen workdesk ledstrip switcher"
    pin:
      number: GPIO4
      inverted: true
    on_double_click:
      - logger.log: "Double Clicked"
      - homeassistant.service:
          service: script.turn_on
          data:
            entity_id: script.setup_on_wled


#KITCHEN AMBIENT LEDSTRIP CONTROL
  - platform: gpio
    id: kitchen_ambient_ledstrip_switcher
    name: "Kitchen ambient ledstrip  switcher"
    pin:
      number: GPIO5
      inverted: true