esphome:
  name: dimmerswitch_bedroom_zone2
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "ThePingInTheNorth"
  password: "lanister"
  ap:
    ssid: "PanicVIFI"
    password: "dubai.2020"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "lanister"
ota:
  password: "lanister"