esphome:
  name: livingroom_dimmer_group_1
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: "ThePingInTheNorth"
  password: "lanister"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Dimmer Group 1"
    password: "XiY1DK9Nr0L0"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
