- alias: "notification lock frontdoor"
  initial_state: true
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: 'LOCK_FRONTDOOR'
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: 'UNLOCK_FRONTDOOR'
  action:
    service: >
      {% if trigger.event.data.action == 'UNLOCK_FRONTDOOR' %}
        lock.unlock
      {% elif  trigger.event.data.action == 'LOCK_FRONTDOOR'%}
        lock.lock
      {% endif %}
    target:
      entity_id: lock.nuki_front_door_lock
    data:
      code: !secret nuki_code