# - id: 'Car optimum for wash'
#   alias: Tell me when I can Clear the Car
#   trigger:
#   - entity_id: binary_sensor.car_wash
#     platform: state
#     from: off
#     to: on
#   action:
#     - service: notify.mobile_app_stefans_iphone
#       data:
#         title: "Home Assistant"
#         message: "You Should Plan to clean the car."
    


#GREJALICA NOTIFIKACIJA
- id: iOS notify terace heater on
  alias: 'Notify when terace heater is ON'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.terace_heater_state
      from: 'off'
      to: 'on'
      for: 00:00:10
  action:
    service: notify.mobile_app_stefans_iphone
    data:
      title: 'ALERT!'
      message: "Upaljena je grejalica na terasi!"
      data:
        push:
          category: "teraceheater" # Needs to match the top level identifier you used in the ios configuration

- alias: iOS action terace heater off
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: TERACEHEATEROFF
  action:
    service: switch.turn_off
    entity_id: switch.terace_heater

#BOJLER NOTIFIKACIJA
- alias: iOS notify bathroom boiler off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.bathroom_boiler
      from: 'on'
      to: 'off'
  action:
    service: notify.mobile_app_stefans_iphone
    data:
      title: 'Kupatilo'
      message: "Bojler je ugašen"
      data:
        actions:
        - action: "BOILERON"
          title: "Uključi bojler"
          authenticationRequired: false


- alias: ios action bathroom boiler on
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: BOILERON
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_boiler

# - alias: iOS notify for laundry
#   initial_state: 'on'
#   trigger:
#     - platform: state
#       entity_id: input_boolean.pickup_laundry
#       from: 'off'
#       to: 'on'
#   action:
#     - service: notify.mobile_app_stefans_iphone
#       data:
#         title: 'Kupatilo'
#         message: "Uzmite veš iz veš mašine"
#         data:
#           actions:
#           - action: "LAUNDRYPICKED"
#             title: "Veš je preuzet"
#             authenticationRequired: false
#     - service: notify.mobile_app_anjas_iphone
#       data:
#         title: 'Kupatilo'
#         message: "Bojler je ugašen"
#         data:
#           title: 'Kupatilo'
#           message: "Anja, molim te pokupi veš iz veš mašine. Hvala, tvoja veš mašina. :)"
#           data:
#             actions:
#             - action: "LAUNDRYPICKED"
#               title: "Veš je preuzet"
#               authenticationRequired: false


- alias: ios action laundry picked up
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: LAUNDRYPICKED
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.pickup_laundry
#ACTIONS
- alias: iOS action residents left house
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: residents_left_house
  action:
    service: script.turn_on
    entity_id: script.residents_left

- alias: iOS action unlock interphone door
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: Unlock Interphone Door
  action:
    service: script.turn_on
    entity_id: script.unlock_interphone_door

- alias: iOS action turn off all media speakers
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: turn_off_all_music
  action:
    service: script.turn_on
    entity_id: script.turn_off_music_all

- alias: iOS action turn off all appliancies (lights and media) #for example good action for GoodNight
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: turn_off_all_appliancies
  action:
    service: script.turn_on
    entity_id: 
      - script.turn_off_music_all
      - script.residents_left

- alias: "Laundry pick up"
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Laundry is picked up'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.pickup_laundry

- alias: "Vacation mode ON"
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "VACATION_MODE_ON"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.vacation_mode